/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface PeripheralERC721PoolInterface extends utils.Interface {
  contractName: "PeripheralERC721Pool";
  functions: {
    "bulkDeposit(address,uint256[])": FunctionFragment;
    "bulkWithdraw(address,uint256[])": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setENSName(address,string)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "withdrawAvailable(address,uint256[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "bulkDeposit",
    values: [string, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "bulkWithdraw",
    values: [string, BigNumberish[]]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setENSName",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawAvailable",
    values: [string, BigNumberish[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "bulkDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bulkWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setENSName", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawAvailable",
    data: BytesLike
  ): Result;

  events: {
    "BulkDeposit(address,uint256[],address)": EventFragment;
    "BulkWithdraw(address,uint256[],address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "WithdrawAvailable(address,uint256[],address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BulkDeposit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BulkWithdraw"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WithdrawAvailable"): EventFragment;
}

export type BulkDepositEvent = TypedEvent<
  [string, BigNumber[], string],
  { pool: string; ids: BigNumber[]; caller: string }
>;

export type BulkDepositEventFilter = TypedEventFilter<BulkDepositEvent>;

export type BulkWithdrawEvent = TypedEvent<
  [string, BigNumber[], string],
  { pool: string; ids: BigNumber[]; caller: string }
>;

export type BulkWithdrawEventFilter = TypedEventFilter<BulkWithdrawEvent>;

export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  { previousOwner: string; newOwner: string }
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export type WithdrawAvailableEvent = TypedEvent<
  [string, BigNumber[], string],
  { pool: string; withdrawnIds: BigNumber[]; caller: string }
>;

export type WithdrawAvailableEventFilter =
  TypedEventFilter<WithdrawAvailableEvent>;

export interface PeripheralERC721Pool extends BaseContract {
  contractName: "PeripheralERC721Pool";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PeripheralERC721PoolInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    bulkDeposit(
      pool: string,
      ids: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    bulkWithdraw(
      pool: string,
      ids: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setENSName(
      registrar: string,
      name: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdrawAvailable(
      pool: string,
      ids: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  bulkDeposit(
    pool: string,
    ids: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  bulkWithdraw(
    pool: string,
    ids: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setENSName(
    registrar: string,
    name: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdrawAvailable(
    pool: string,
    ids: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    bulkDeposit(
      pool: string,
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    bulkWithdraw(
      pool: string,
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setENSName(
      registrar: string,
      name: string,
      overrides?: CallOverrides
    ): Promise<string>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawAvailable(
      pool: string,
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "BulkDeposit(address,uint256[],address)"(
      pool?: null,
      ids?: null,
      caller?: null
    ): BulkDepositEventFilter;
    BulkDeposit(pool?: null, ids?: null, caller?: null): BulkDepositEventFilter;

    "BulkWithdraw(address,uint256[],address)"(
      pool?: null,
      ids?: null,
      caller?: null
    ): BulkWithdrawEventFilter;
    BulkWithdraw(
      pool?: null,
      ids?: null,
      caller?: null
    ): BulkWithdrawEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;

    "WithdrawAvailable(address,uint256[],address)"(
      pool?: null,
      withdrawnIds?: null,
      caller?: null
    ): WithdrawAvailableEventFilter;
    WithdrawAvailable(
      pool?: null,
      withdrawnIds?: null,
      caller?: null
    ): WithdrawAvailableEventFilter;
  };

  estimateGas: {
    bulkDeposit(
      pool: string,
      ids: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    bulkWithdraw(
      pool: string,
      ids: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setENSName(
      registrar: string,
      name: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdrawAvailable(
      pool: string,
      ids: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    bulkDeposit(
      pool: string,
      ids: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    bulkWithdraw(
      pool: string,
      ids: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setENSName(
      registrar: string,
      name: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdrawAvailable(
      pool: string,
      ids: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
