/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface PoolFactoryInterface extends utils.Interface {
  contractName: "PoolFactory";
  functions: {
<<<<<<< HEAD
    "createPool(string,string,address)": FunctionFragment;
    "pools(address)": FunctionFragment;
=======
    "allPools(uint256)": FunctionFragment;
    "allPoolsLength()": FunctionFragment;
    "createPool(address)": FunctionFragment;
    "getPool(address)": FunctionFragment;
>>>>>>> origin/main
  };

  encodeFunctionData(
    functionFragment: "allPools",
    values: [BigNumberish]
  ): string;
<<<<<<< HEAD
  encodeFunctionData(functionFragment: "pools", values: [string]): string;

  decodeFunctionResult(functionFragment: "createPool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pools", data: BytesLike): Result;
=======
  encodeFunctionData(
    functionFragment: "allPoolsLength",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "createPool", values: [string]): string;
  encodeFunctionData(functionFragment: "getPool", values: [string]): string;

  decodeFunctionResult(functionFragment: "allPools", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "allPoolsLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createPool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getPool", data: BytesLike): Result;
>>>>>>> origin/main

  events: {
    "CreatePool(string,string,address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CreatePool"): EventFragment;
}

export type CreatePoolEvent = TypedEvent<
  [string, string, string, string],
  { name: string; symbol: string; asset: string; pool: string }
>;

export type CreatePoolEventFilter = TypedEventFilter<CreatePoolEvent>;

export interface PoolFactory extends BaseContract {
  contractName: "PoolFactory";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PoolFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    allPools(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    allPoolsLength(overrides?: CallOverrides): Promise<[BigNumber]>;

    createPool(
      asset: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

<<<<<<< HEAD
    pools(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;
=======
    getPool(arg0: string, overrides?: CallOverrides): Promise<[string]>;
>>>>>>> origin/main
  };

  allPools(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  allPoolsLength(overrides?: CallOverrides): Promise<BigNumber>;

  createPool(
    asset: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

<<<<<<< HEAD
  pools(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  callStatic: {
    createPool(
      name: string,
      symbol: string,
      asset: string,
      overrides?: CallOverrides
    ): Promise<void>;

    pools(arg0: string, overrides?: CallOverrides): Promise<boolean>;
=======
  getPool(arg0: string, overrides?: CallOverrides): Promise<string>;

  callStatic: {
    allPools(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    allPoolsLength(overrides?: CallOverrides): Promise<BigNumber>;

    createPool(asset: string, overrides?: CallOverrides): Promise<void>;

    getPool(arg0: string, overrides?: CallOverrides): Promise<string>;
>>>>>>> origin/main
  };

  filters: {
    "CreatePool(string,string,address,address)"(
      name?: null,
      symbol?: null,
      asset?: string | null,
      pool?: string | null
    ): CreatePoolEventFilter;
    CreatePool(
      name?: null,
      symbol?: null,
      asset?: string | null,
      pool?: string | null
    ): CreatePoolEventFilter;
  };

  estimateGas: {
    allPools(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    allPoolsLength(overrides?: CallOverrides): Promise<BigNumber>;

    createPool(
      asset: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

<<<<<<< HEAD
    pools(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;
=======
    getPool(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;
>>>>>>> origin/main
  };

  populateTransaction: {
    allPools(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    allPoolsLength(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    createPool(
      asset: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

<<<<<<< HEAD
    pools(
=======
    getPool(
>>>>>>> origin/main
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
