/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface PoolFactoryInterface extends utils.Interface {
  contractName: "PoolFactory";
  functions: {
    "createPool(string,string,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "createPool",
    values: [string, string, string]
  ): string;

  decodeFunctionResult(functionFragment: "createPool", data: BytesLike): Result;

  events: {
    "CreatePool(string,string,address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CreatePool"): EventFragment;
}

export type CreatePoolEvent = TypedEvent<
  [string, string, string, string],
  { name: string; symbol: string; asset: string; pool: string }
>;

export type CreatePoolEventFilter = TypedEventFilter<CreatePoolEvent>;

export interface PoolFactory extends BaseContract {
  contractName: "PoolFactory";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PoolFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createPool(
      name: string,
      symbol: string,
      asset: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  createPool(
    name: string,
    symbol: string,
    asset: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    createPool(
      name: string,
      symbol: string,
      asset: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "CreatePool(string,string,address,address)"(
      name?: null,
      symbol?: null,
      asset?: string | null,
      pool?: string | null
    ): CreatePoolEventFilter;
    CreatePool(
      name?: null,
      symbol?: null,
      asset?: string | null,
      pool?: string | null
    ): CreatePoolEventFilter;
  };

  estimateGas: {
    createPool(
      name: string,
      symbol: string,
      asset: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createPool(
      name: string,
      symbol: string,
      asset: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
